### PR TITLE
Deleted unused file

### PR DESCRIPTION
**Pull request by aleksspeaker**
`action` mentioned twice in function params and `nextState` was missing

Checklist
----

_Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

 - [ ] I have added tests that prove my fix is effective or that my feature works.
 - [ ] I have added all necessary documentation (if appropriate)

What was done
----

_...Describe the fix you made, the feature you built, or the documentation you added_

Associated Issues
----
 - _list any associated issue numbers here_

:heart: Thanks
----
Thanks for taking the time to help out with the project, it's much appreciated :slightly_smiling_face:

### CODE REVIEW

**Comment by ttmarek** [comment]
Huh. We actually don't use this file at all in the docs. We can get rid of it entirely. I must have missed it when re-writing them. Here are the new API docs:

 - https://rangle.gitbook.io/redux-beacon/index-1
 - https://rangle.gitbook.io/redux-beacon/index-1/event-definition

Do you mind deleting this file entirely in this pull request? So as to not confuse others.

**Comment by aleksspeaker** [comment]
Yea, sure!

**Comment by aleksspeaker** [comment]
I guess there's something with links
image

**Comment by ttmarek** [comment]
This is awesome. Thank you! I appreciate it.

About the GoogleTagManager link. I'm not really sure why that's happening. Gitbook seems to be doing it automatically. I'll look into it later this week. Thanks for bringing this to my attention.

**Comment by aleksspeaker** [comment]
🍻

**Pull request merged**
