### PR TITLE
eventFields can return an array of events

### PR DESCRIPTION
**Pull request by coluccini**
This PR add the possibility of triggering more than one event from a single eventDefinition.
Example:
```javascript
dispatch(setFiltersAction({
  foo: 1,
  bar: 2,
  xyz: 3,
}))

const filtersChange = {
  eventFields: action => {
    const events = [];
    Object.entries(action.data).forEach(([key, value]) => {
      events.push({
        hitType: 'event',
        eventCategory: 'filters',
        eventAction: 'set',
        eventLabel: key,
        eventValue: value,
      })
    });
    return events;
  },
  eventSchema: {
    eventValue: value => value !== '0',
  },
};

const eventsMap = {
  SET_FILTERS: filtersChange,
};
```

### CODE REVIEW

**Comment by ttmarek** [comment]
@coluccini this is great. Thanks so much! :1st_place_medal: :trophy: 

This will definitely be included in the next release, which will probably be our first major release.

**Comment by coluccini** [comment]
Thanks to you for this amazing module, @ttmarek!

**Comment by coluccini** [comment]
@ttmarek, do you have an estimated on when the next release will be done? I'm now using this straight from github and works fine on my local machine, but it's giving me problems with CI and deploys 😢 
Or at least do you know a way to make a `yarn add` from github that triggers the build script?
Thanks!

**Comment by ttmarek** [comment]
@coluccini I just published a new release with these changes `v0.4.0`.

**Comment by coluccini** [comment]
You're the best!

**Pull request merged**
