### PR TITLE
Add documentation for custom dimensions

### PR DESCRIPTION
**Pull request by bzswords**
This just adds documentation on how to take advantage of the new hit types added by @djw27 in their PR. 

@ttmarek forked off of @djw27's project. Not sure if this is the what you were expecting. I can change the base of this fork if needed.

### CODE REVIEW

**Comment by ttmarek** [comment]
@bzswords @djw27 thanks for all your hard work on this guys! :100: 
It's much appreciated :slightly_smiling_face:.

I'll let you know once these changes are published to npm.

**Comment by djw27** [comment]
@bzswords @ttmarek thanks for getting this merged!

**Comment by bzswords** [comment]
@ttmarek any update on when this will be published?

**Comment by ttmarek** [comment]
Hey @bzswords. Sorry, some clients are in town this week so I haven't had any open evenings to work on the next release. It is so so close though. I wrote a checklist of what's left in this issue here:
https://github.com/rangle/redux-beacon/issues/180

In the meantime I would opt for simple copy-pasting the entire `react-native-google-analytics` target into your repo. In the next release this will be published separately under `@redux-beacon/react-native-google-analytics` as described [here](https://github.com/rangle/redux-beacon/blob/master/docs/targets/react-native-google-analytics.md)

Any help would be greatly appreciated if you can spare a moment or two. Adding typescript definitions for each event-helper would be fairly straightforward and a huge win.

**Comment by bzswords** [comment]
@ttmarek thank you for the response, i totally understand. i may actually have time this weekend to contribute. ill comment on that checklist if so.

**Pull request merged**
